language: android
jdk: oraclejdk7
android:
  components:
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - build-tools-21.1.2
    - android-18
env:
  global:
    - TERM=dumb
script:
    - ./gradlew test
