language: android
jdk: oraclejdk7
android:
  components:
  - extra-android-m2repository
  - extra-google-m2repository
  - build-tools-21.1.1
  - android-18
script:
  - "./gradlew clean assemble test"
after_script:
  - "ls app/build"
  - "cat cat app/build/test-report/debug/classes/jp.water_cell.android.template.MainActivityRobolectricTest.html"